title: "Calvin"
description: "A portfolio showcasing Data Analytics projects that I have completed"
theme: jekyll-theme-cayman


#title:  "Calvin Thai"
#theme: jekyll-theme-cayman
#description: "A portfolio showcasing Data Analytics projects that I have completed"
#show_downloads: false

